# TetrapodGenerator.py
# Fusion 360 Add-in - æœ€çµ‚å®Œæˆç‰ˆ

import adsk.core, adsk.fusion, traceback
import math

_app = None
_ui = None
_handlers = []

# åˆæœŸè¨­å®š
LEG_LENGTH = 8.0  # cm
LEG_BASE_DIAMETER = 5.0  # cm
LEG_TIP_DIAMETER = 4.0  # cm
CENTER_FILLET_RADIUS = 2.5  # cmï¼ˆæ¥åˆéƒ¨ã®ã¿ï¼‰
TIP_FILLET_RADIUS = 0.3  # cmï¼ˆå…ˆç«¯ã®è§’ä¸¸ï¼‰

def run(context):
    try:
        global _app, _ui
        _app = adsk.core.Application.get()
        _ui = _app.userInterface
        
        cmdDef = _ui.commandDefinitions.itemById('TetrapodGenerator')
        if cmdDef:
            cmdDef.deleteMe()
        
        cmdDef = _ui.commandDefinitions.addButtonDefinition(
            'TetrapodGenerator',
            'ãƒ†ãƒˆãƒ©ãƒãƒƒãƒ‰ç”Ÿæˆ ğŸ—ï¸',
            'ãƒªã‚¢ãƒ«ãªãƒ†ãƒˆãƒ©ãƒãƒƒãƒ‰ã‚’ç”Ÿæˆ'
        )
        
        onCommandCreated = TetrapodCommandCreatedHandler()
        cmdDef.commandCreated.add(onCommandCreated)
        _handlers.append(onCommandCreated)
        
        added = False
        try:
            utilPanel = _ui.allToolbarPanels.itemById('ToolsTab')
            if utilPanel:
                cntrl = utilPanel.controls.addCommand(cmdDef)
                cntrl.isPromotedByDefault = True
                cntrl.isPromoted = True
                added = True
        except:
            pass
        
        if not added:
            try:
                createPanel = _ui.allToolbarPanels.itemById('SolidCreatePanel')
                if createPanel:
                    cntrl = createPanel.controls.addCommand(cmdDef)
                    cntrl.isPromotedByDefault = True
                    added = True
            except:
                pass
        
        if added:
            _ui.messageBox('âœ… ã‚¢ãƒ‰ã‚ªãƒ³èª­ã¿è¾¼ã¿å®Œäº†!')
        
    except:
        if _ui:
            _ui.messageBox('âŒ å¤±æ•—:\n{}'.format(traceback.format_exc()))

def stop(context):
    try:
        for panelId in ['ToolsTab', 'SolidCreatePanel']:
            try:
                panel = _ui.allToolbarPanels.itemById(panelId)
                if panel:
                    cmd = panel.controls.itemById('TetrapodGenerator')
                    if cmd:
                        cmd.deleteMe()
            except:
                pass
        
        cmdDef = _ui.commandDefinitions.itemById('TetrapodGenerator')
        if cmdDef:
            cmdDef.deleteMe()
    except:
        pass

class TetrapodCommandCreatedHandler(adsk.core.CommandCreatedEventHandler):
    def __init__(self):
        super().__init__()
        
    def notify(self, args):
        try:
            cmd = args.command
            inputs = cmd.commandInputs
            
            inputs.addValueInput('legLength', 'è„šã®é•·ã• (cm)', 'cm', 
                                adsk.core.ValueInput.createByReal(LEG_LENGTH))
            inputs.addValueInput('legBaseDiameter', 'è„šã®æ ¹å…ƒç›´å¾„ (cm)', 'cm',
                                adsk.core.ValueInput.createByReal(LEG_BASE_DIAMETER))
            inputs.addValueInput('legTipDiameter', 'è„šã®å…ˆç«¯ç›´å¾„ (cm)', 'cm',
                                adsk.core.ValueInput.createByReal(LEG_TIP_DIAMETER))
            inputs.addValueInput('centerFilletRadius', 'æ¥åˆéƒ¨ãƒ•ã‚£ãƒ¬ãƒƒãƒˆåŠå¾„ (cm)', 'cm',
                                adsk.core.ValueInput.createByReal(CENTER_FILLET_RADIUS))
            inputs.addValueInput('tipFilletRadius', 'å…ˆç«¯è§’ä¸¸åŠå¾„ (cm)', 'cm',
                                adsk.core.ValueInput.createByReal(TIP_FILLET_RADIUS))
            
            onExecute = TetrapodCommandExecuteHandler()
            cmd.execute.add(onExecute)
            _handlers.append(onExecute)
            
        except:
            _ui.messageBox('UIä½œæˆå¤±æ•—:\n{}'.format(traceback.format_exc()))

class TetrapodCommandExecuteHandler(adsk.core.CommandEventHandler):
    def __init__(self):
        super().__init__()
        
    def notify(self, args):
        try:
            inputs = args.command.commandInputs
            
            legLength = inputs.itemById('legLength').value
            legBaseDiameter = inputs.itemById('legBaseDiameter').value
            legTipDiameter = inputs.itemById('legTipDiameter').value
            centerFilletRadius = inputs.itemById('centerFilletRadius').value
            tipFilletRadius = inputs.itemById('tipFilletRadius').value
            
            createTetrapod(legLength, legBaseDiameter, legTipDiameter, 
                          centerFilletRadius, tipFilletRadius)
            
            _ui.messageBox('ğŸ‰ ãƒ†ãƒˆãƒ©ãƒãƒƒãƒ‰ç”Ÿæˆå®Œäº†!')
            
        except:
            _ui.messageBox('ç”Ÿæˆå¤±æ•—:\n{}'.format(traceback.format_exc()))

def createTetrapod(legLength, legBaseDiameter, legTipDiameter, 
                   centerFilletRadius, tipFilletRadius):
    """ãƒ†ãƒˆãƒ©ãƒãƒƒãƒ‰ç”Ÿæˆ"""
    
    design = _app.activeProduct
    rootComp = design.rootComponent
    
    occurrence = rootComp.occurrences.addNewComponent(adsk.core.Matrix3D.create())
    comp = occurrence.component
    comp.name = 'Tetrapod'
    
    # æ­£å››é¢ä½“é…ç½®
    legVectors = [
        (0, 0, 1),
        (2*math.sqrt(2)/3, 0, -1/3),
        (-math.sqrt(2)/3, math.sqrt(2/3), -1/3),
        (-math.sqrt(2)/3, -math.sqrt(2/3), -1/3)
    ]
    
    for vec in legVectors:
        createLeg(comp, legLength, legBaseDiameter, legTipDiameter, vec)
    
    # çµåˆ
    combineAllBodies(comp)
    
    # å…ˆç«¯ã®è§’ä¸¸ï¼ˆå…ˆã«å®Ÿè¡Œï¼‰
    addTipFillets(comp, tipFilletRadius)
    
    # æ¥åˆéƒ¨ã®ãƒ•ã‚£ãƒ¬ãƒƒãƒˆï¼ˆå¾Œã§å®Ÿè¡Œï¼‰
    addCenterFillets(comp, centerFilletRadius)

def createLeg(comp, length, baseDiameter, tipDiameter, direction):
    """è„šä½œæˆ"""
    
    sketches = comp.sketches
    xyPlane = comp.xYConstructionPlane
    
    # æ ¹å…ƒ
    baseSketch = sketches.add(xyPlane)
    baseRadius = baseDiameter / 2
    baseSketch.sketchCurves.sketchCircles.addByCenterRadius(
        adsk.core.Point3D.create(0, 0, 0),
        baseRadius
    )
    
    # å…ˆç«¯å¹³é¢
    planes = comp.constructionPlanes
    planeInput = planes.createInput()
    offsetValue = adsk.core.ValueInput.createByReal(length)
    planeInput.setByOffset(xyPlane, offsetValue)
    tipPlane = planes.add(planeInput)
    
    # å…ˆç«¯
    tipSketch = sketches.add(tipPlane)
    tipRadius = tipDiameter / 2
    tipSketch.sketchCurves.sketchCircles.addByCenterRadius(
        adsk.core.Point3D.create(0, 0, 0),
        tipRadius
    )
    
    # Loft
    lofts = comp.features.loftFeatures
    loftInput = lofts.createInput(adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    
    loftSections = loftInput.loftSections
    loftSections.add(baseSketch.profiles.item(0))
    loftSections.add(tipSketch.profiles.item(0))
    
    loftInput.isSolid = True
    loftFeature = lofts.add(loftInput)
    
    body = loftFeature.bodies.item(0)
    rotateBody(comp, body, direction)
    
    tipPlane.deleteMe()

def rotateBody(comp, body, direction):
    """å›è»¢"""
    
    x, y, z = direction
    
    defaultDir = adsk.core.Vector3D.create(0, 0, 1)
    targetDir = adsk.core.Vector3D.create(x, y, z)
    targetDir.normalize()
    
    angle = defaultDir.angleTo(targetDir)
    
    if angle > 0.001:
        axis = defaultDir.crossProduct(targetDir)
        axis.normalize()
        
        origin = adsk.core.Point3D.create(0, 0, 0)
        transform = adsk.core.Matrix3D.create()
        transform.setToRotation(angle, axis, origin)
        
        moveFeats = comp.features.moveFeatures
        bodyCol = adsk.core.ObjectCollection.create()
        bodyCol.add(body)
        
        moveInput = moveFeats.createInput(bodyCol, transform)
        moveFeats.add(moveInput)

def combineAllBodies(comp):
    """çµåˆ"""
    
    bodies = comp.bRepBodies
    if bodies.count < 2:
        return
    
    targetBody = bodies.item(0)
    toolBodies = adsk.core.ObjectCollection.create()
    
    for i in range(1, bodies.count):
        toolBodies.add(bodies.item(i))
    
    combines = comp.features.combineFeatures
    combineInput = combines.createInput(targetBody, toolBodies)
    combineInput.operation = adsk.fusion.FeatureOperations.JoinFeatureOperation
    combineInput.isKeepToolBodies = False
    combines.add(combineInput)

def addTipFillets(comp, radius):
    """å…ˆç«¯ã®å††ã®ã‚¨ãƒƒã‚¸ã‚’è§’ä¸¸ã«"""
    
    bodies = comp.bRepBodies
    if bodies.count == 0:
        return
    
    body = bodies.item(0)
    fillets = comp.features.filletFeatures
    edgeCol = adsk.core.ObjectCollection.create()
    
    # å…ˆç«¯ã®å††å½¢ã‚¨ãƒƒã‚¸ï¼ˆé•·ã„ã‚¨ãƒƒã‚¸ï¼‰ã‚’æ¤œå‡º
    for edge in body.edges:
        # å††å½¢ã®ã‚¨ãƒƒã‚¸ã¯é•·ã•ãŒä¸€å®šç¯„å›²
        if 8 < edge.length < 15:  # å…ˆç«¯å††å‘¨ã®ã‚¨ãƒƒã‚¸
            edgeCol.add(edge)
    
    if edgeCol.count > 0:
        try:
            filletInput = fillets.createInput()
            filletInput.addConstantRadiusEdgeSet(
                edgeCol, 
                adsk.core.ValueInput.createByReal(radius), 
                True
            )
            fillets.add(filletInput)
        except:
            pass

def addCenterFillets(comp, radius):
    """æ¥åˆéƒ¨ã®ãƒ•ã‚£ãƒ¬ãƒƒãƒˆï¼ˆä¸­å¿ƒéƒ¨ã®ã¿ï¼‰"""
    
    bodies = comp.bRepBodies
    if bodies.count == 0:
        return
    
    body = bodies.item(0)
    fillets = comp.features.filletFeatures
    edgeCol = adsk.core.ObjectCollection.create()
    
    # ä¸­å¿ƒä»˜è¿‘ã®çŸ­ã„ã‚¨ãƒƒã‚¸ã®ã¿é¸æŠ
    centerPoint = adsk.core.Point3D.create(0, 0, 0)
    
    for edge in body.edges:
        # ã‚¨ãƒƒã‚¸ã®ä¸­ç‚¹ã‚’å–å¾—
        evaluator = edge.evaluator
        success, startParam, endParam = evaluator.getParameterExtents()
        if success:
            midParam = (startParam + endParam) / 2
            success, midPoint = evaluator.getPointAtParameter(midParam)
            
            if success:
                # ä¸­å¿ƒã‹ã‚‰è¿‘ã„ & çŸ­ã„ã‚¨ãƒƒã‚¸
                distance = centerPoint.distanceTo(midPoint)
                if distance < radius * 2 and edge.length < radius * 1.5:
                    edgeCol.add(edge)
    
    if edgeCol.count > 0:
        try:
            filletInput = fillets.createInput()
            filletInput.addConstantRadiusEdgeSet(
                edgeCol, 
                adsk.core.ValueInput.createByReal(radius), 
                True
            )
            filletInput.isG2 = False
            filletInput.isRollingBallCorner = True
            fillets.add(filletInput)
        except:
            pass